# Generated by Django 3.1.7 on 2021-04-28 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personId', models.IntegerField()),
                ('personName', models.CharField(max_length=70)),
                ('personPost', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TimeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeID', models.IntegerField()),
                ('entryTime', models.TimeField()),
                ('exitTime', models.TimeField()),
                ('date', models.DateField()),
                ('timeSpent', models.IntegerField()),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPs.peopledetails')),
            ],
        ),
        migrations.CreateModel(
            name='OffenderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offenderId', models.IntegerField()),
                ('offenderRecords', models.TextField(max_length=250)),
                ('offenderName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPs.peopledetails')),
            ],
        ),
    ]
