# Generated by Django 3.1.7 on 2021-04-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=70)),
                ('customerEntryTime', models.TimeField()),
                ('customerExitTime', models.TimeField()),
                ('dateToday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Offender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offenderName', models.CharField(max_length=70)),
                ('offenderEntryTime', models.TimeField()),
                ('offenderExitTime', models.TimeField()),
                ('dateToday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffName', models.CharField(max_length=70)),
                ('staffEntryTime', models.TimeField()),
                ('staffExitTime', models.TimeField()),
                ('dateToday', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='timedetails',
            name='personId',
        ),
        migrations.DeleteModel(
            name='OffenderDetails',
        ),
        migrations.DeleteModel(
            name='PeopleDetails',
        ),
        migrations.DeleteModel(
            name='TimeDetails',
        ),
    ]
