# Generated by Django 3.1.7 on 2021-04-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPs', '0002_auto_20210429_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personNames', models.CharField(max_length=70)),
                ('personEntryTime', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Offender',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
