# Generated by Django 3.1.7 on 2021-05-01 08:41

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('APPs', '0003_auto_20210430_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personNames', models.CharField(max_length=70)),
                ('person_post', models.CharField(max_length=50)),
                ('personExitTime', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='entries',
            name='person_post',
            field=models.CharField(default='customers', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entries',
            name='personNames',
            field=models.CharField(default='customers', max_length=70),
        ),
    ]
